# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.hostname = "lfs"
  config.vm.box = "debian/contrib-stretch64"
  config.vm.network "forwarded_port", guest: 80, host: 8000, host_ip: "0.0.0.0"
  config.vm.network "forwarded_port", guest: 443, host: 44300, host_ip: "0.0.0.0"
  config.vm.synced_folder "..", "/vagrant"

  #config.ssh.forward_x11 = true
  config.ssh.forward_agent = true  

  config.vm.provider "virtualbox" do |vb|
    vb.name = "lfs"
    vb.memory = "512"
    config.vm.provision :shell, path: "vagrant_bootstrap.sh"
  end

end
