# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lfs_server', '0002_auto_20150501_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lfsobject',
            name='file',
            field=models.FileField(upload_to='lfs'),
        ),
    ]
